export const ENABLE_FORM_NEW_PROJECT = "ENABLE_FORM_NEW_PROJECT";
export const OBTAIN_PROJECTS = "OBTAIN_PROJECTS";
export const ADD_PROJECT = "ADD_PROJECTS";
export const ERROR_PROJECT_FORM = "ERROR_PROJECT_FORM";
export const FOCUS_PROJECT = "FOCUS_PROJECT";
export const DELETE_PROJECT = "DELETE_PROEJCT";
export const ERROR_PROJECT = "ERROR_PROJECT";

export const OBTAIN_TASKS = "OBTAIN_TASKS";
export const ADD_TASK = "ADD_TASK";
export const ERROR_TASK_FORM = "ERROR_TASK_FORM";
export const DELETE_TASK = "DELETE_TASK";
export const CHANGE_TASK_STATUS = "CHANGE_TASK_STATUS";
export const SELECT_CURRENT_TASK = "SELECT_CURRENT_TASK";
export const UPDATE_TASK = "UPDATE_TASK";

export const SHOW_ALERT = "SHOW ALERT";
export const HIDE_ALERT = "HIDE ALERT";

export const SUCCESS_REGISTER = "SUCCESS_REGISTER";
export const ALERT_REGISTER = "ALERT_REGISTER";
export const OBTAIN_USER = "OBTAIN_USER";
export const SUCCES_LOGIN = "SUCCES_LOGIN";
export const ALERT_LOGIN = "ALERT_LOGIN";
export const LOGOUT = "LOGOUT";
