export const ENABLE_FORM_NEW_PROJECT = "ENABLE_FORM_NEW_PROJECT";
export const OBTAIN_PROJECTS = "OBTAIN_PROJECTS";
export const ADD_PROJECT = "ADD_PROJECTS";
export const ERROR_PROJECT_FORM = "ERROR_PROJECT_FORM";
export const FOCUS_PROJECT = "FOCUS_PROJECT";
export const DELETE_PROJECT = "DELETE_PROEJCT";

export const OBTAIN_TASKS = "OBTAIN_TASKS";
export const ADD_TASK = "ADD_TASK";
export const ERROR_TASK_FORM = "ERROR_TASK_FORM";
export const DELETE_TASK = "DELETE_TASK";
